/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: leMstrx (https://sketchfab.com/leMstrx)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/detailed-grass-by-lemstrx-b55c82301f5b4b2099e3fee553ba3ec2
title: Detailed Grass - by leMstrx
*/

import React, { Suspense, useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export function Grass02(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/grass/grass02/scene.gltf')
  return (
    <Suspense fallback={null}>
      <group ref={group} {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group
              rotation={[Math.PI, 1.37, -Math.PI]}
              scale={[25.33, 16.69, 22.58]}
            >
              <mesh
                material={materials.Grass_1}
                geometry={nodes.Grass_1012_Grass_1_0.geometry}
              />
              <mesh
                material={materials.Grass_2}
                geometry={nodes.Grass_1012_Grass_2_0.geometry}
              />
            </group>
          </group>
        </group>
      </group>
    </Suspense>
  )
}

useGLTF.preload('/models/grass/grass02/scene.gltf')
