/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: F A L C O N (https://sketchfab.com/qewr1324)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/grass-2-3e564f62f90845a1adda9c46fdeace52
title: Grass_2
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export function Grass03(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/grass/grass03/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[493.05, 254.33, 617.61]} rotation={[-Math.PI, 0.84, 2.89]} />
          <group position={[28.35, 0, 472.44]} rotation={[0, 0, 0]} scale={[0.39, 0.39, 0.39]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low__0.geometry} />
          </group>
          <group position={[0, 0, 472.44]} rotation={[0, 0, 0]} scale={[0.39, 0.39, 0.39]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med__0.geometry} />
          </group>
          <group position={[-28.35, 0, 472.44]} rotation={[0, 0, 0]} scale={[0.39, 0.39, 0.39]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High__0.geometry} />
          </group>
          <group position={[-207.34, 0, 267.45]} rotation={[0.07, 0.18, 0.16]} scale={[1.07, 0.71, 1.38]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_0__0.geometry} />
          </group>
          <group position={[-162.34, 0, 272.17]} rotation={[0, -0.05, -0.13]} scale={[0.96, 1.14, 1.16]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_1__0.geometry} />
          </group>
          <group position={[-197.92, 0, 248.05]} rotation={[0.2, 0.06, -0.22]} scale={[1.34, 1.03, 0.59]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_2__0.geometry} />
          </group>
          <group position={[-181.22, 0, 240.89]} rotation={[0.2, -0.06, 0.11]} scale={[1.44, 0.98, 0.82]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_3__0.geometry} />
          </group>
          <group position={[-177.88, 0, 183.77]} rotation={[0.03, -0.17, -0.15]} scale={[1.15, 1.48, 1.39]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_4__0.geometry} />
          </group>
          <group position={[-200.55, 0, 175.44]} rotation={[0.17, -0.04, -0.01]} scale={[0.79, 1.1, 0.61]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_5__0.geometry} />
          </group>
          <group position={[-238.99, 0, 109.36]} rotation={[0.01, 0.03, -0.12]} scale={[0.65, 0.57, 0.94]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_6__0.geometry} />
          </group>
          <group position={[-155.22, 0, 66.97]} rotation={[-0.01, 0.05, 0.12]} scale={[0.57, 0.53, 1.25]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_7__0.geometry} />
          </group>
          <group position={[-151.34, 0, 50.94]} rotation={[0.05, 0.13, -0.03]} scale={[0.51, 0.9, 1.36]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_8__0.geometry} />
          </group>
          <group position={[-227.5, 0, 50.03]} rotation={[0.2, -0.13, 0.19]} scale={[1.03, 0.67, 0.81]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_9__0.geometry} />
          </group>
          <group position={[-246.08, 0, -21.02]} rotation={[-0.2, -0.13, -0.13]} scale={[1.08, 1.45, 0.51]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_10__0.geometry} />
          </group>
          <group position={[-186.23, 0, -61.14]} rotation={[-0.13, 0.12, -0.09]} scale={[0.58, 0.64, 1.41]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_11__0.geometry} />
          </group>
          <group position={[-207.69, 0, -23.5]} rotation={[0.18, -0.09, 0.19]} scale={[0.9, 0.57, 1.31]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_12__0.geometry} />
          </group>
          <group position={[-201.91, 0, -59.68]} rotation={[-0.15, 0.01, -0.1]} scale={[0.87, 1.29, 0.76]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_13__0.geometry} />
          </group>
          <group position={[-178.63, 0, -111.02]} rotation={[0.21, 0.03, 0.1]} scale={[0.63, 0.76, 1.24]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_14__0.geometry} />
          </group>
          <group position={[-243.26, 0, -147.87]} rotation={[-0.17, -0.13, 0.01]} scale={[0.52, 1.34, 0.72]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_15__0.geometry} />
          </group>
          <group position={[-241.03, 0, -170.72]} rotation={[-0.2, 0.09, 0.21]} scale={[1, 1.16, 0.87]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_16__0.geometry} />
          </group>
          <group position={[-245.87, 0, -245.42]} rotation={[0.05, -0.01, -0.07]} scale={[1.48, 1.45, 1.36]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_17__0.geometry} />
          </group>
          <group position={[-176.99, 0, -244.04]} rotation={[0.18, 0.03, 0.04]} scale={[1.11, 0.52, 1.42]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_18__0.geometry} />
          </group>
          <group position={[-149.45, 0, -263.99]} rotation={[0.01, 0.17, 0.02]} scale={[0.92, 0.89, 1.45]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_19__0.geometry} />
          </group>
          <group position={[-206.27, 0, 216.69]} rotation={[0, -0.13, -0.11]} scale={[1.39, 0.97, 0.74]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_20__0.geometry} />
          </group>
          <group position={[-158.11, 0, 196]} rotation={[-0.12, 0.02, 0.16]} scale={[1.17, 0.94, 1.44]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_21__0.geometry} />
          </group>
          <group position={[-140.08, 0, 177.68]} rotation={[-0.01, -0.15, 0.03]} scale={[1.44, 0.82, 1.37]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_22__0.geometry} />
          </group>
          <group position={[-124.41, 0, 223.58]} rotation={[-0.18, 0.02, 0.01]} scale={[1.36, 1.49, 0.57]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_23__0.geometry} />
          </group>
          <group position={[-195.74, 0, 193.26]} rotation={[-0.19, -0.12, -0.1]} scale={[1.21, 0.84, 0.91]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_24__0.geometry} />
          </group>
          <group position={[-162.6, 0, 149.1]} rotation={[0.06, 0.02, -0.07]} scale={[1.46, 0.65, 1.02]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_25__0.geometry} />
          </group>
          <group position={[-147.02, 0, 37.32]} rotation={[0.18, 0.01, -0.13]} scale={[0.72, 1.01, 0.88]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_26__0.geometry} />
          </group>
          <group position={[-169.61, 0, 97.59]} rotation={[0.09, 0.02, 0.05]} scale={[1.47, 1.17, 0.57]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_27__0.geometry} />
          </group>
          <group position={[-131.57, 0, 5.73]} rotation={[0.01, -0.2, 0.04]} scale={[0.97, 0.64, 0.94]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_28__0.geometry} />
          </group>
          <group position={[-215.96, 0, -35.61]} rotation={[-0.17, 0.15, -0.15]} scale={[0.9, 0.51, 1.02]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_29__0.geometry} />
          </group>
          <group position={[-133.59, 0, -54.01]} rotation={[-0.07, 0.19, -0.14]} scale={[1.14, 0.73, 1.31]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_30__0.geometry} />
          </group>
          <group position={[-145.42, 0, -19.98]} rotation={[-0.08, 0.13, 0.06]} scale={[0.61, 1.29, 1.27]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_31__0.geometry} />
          </group>
          <group position={[-170.78, 0, -129.23]} rotation={[0.12, 0.2, -0.05]} scale={[0.51, 0.91, 0.86]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_32__0.geometry} />
          </group>
          <group position={[-208, 0, -125.05]} rotation={[0.05, 0.07, -0.14]} scale={[0.51, 1.02, 1.47]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_33__0.geometry} />
          </group>
          <group position={[-145.5, 0, -155.64]} rotation={[0.1, 0.12, 0.04]} scale={[0.65, 1.24, 0.87]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_34__0.geometry} />
          </group>
          <group position={[-199.09, 0, -176.35]} rotation={[0, 0.09, -0.17]} scale={[1.12, 0.75, 1.28]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_35__0.geometry} />
          </group>
          <group position={[-209.07, 0, -209.48]} rotation={[-0.09, 0.15, 0.16]} scale={[0.5, 0.62, 1.13]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_36__0.geometry} />
          </group>
          <group position={[-178.88, 0, -212.52]} rotation={[0.07, 0.19, 0.1]} scale={[0.58, 0.75, 1.35]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_37__0.geometry} />
          </group>
          <group position={[-179.29, 0, -306.32]} rotation={[-0.2, 0.13, 0.17]} scale={[1.49, 0.77, 0.97]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_38__0.geometry} />
          </group>
          <group position={[-192.16, 0, -326.42]} rotation={[-0.17, -0.04, 0.12]} scale={[0.57, 1.16, 1.14]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_39__0.geometry} />
          </group>
          <group position={[-125.3, 0, 302.51]} rotation={[0.14, -0.12, 0.09]} scale={[1.49, 0.88, 1.2]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_40__0.geometry} />
          </group>
          <group position={[-132.58, 0, 281.97]} rotation={[-0.09, -0.15, -0.12]} scale={[0.87, 1.39, 1.12]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_41__0.geometry} />
          </group>
          <group position={[-178.2, 0, 277.73]} rotation={[0.11, 0.09, 0.04]} scale={[1.25, 1.3, 1.14]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_42__0.geometry} />
          </group>
          <group position={[-132.01, 0, 157.59]} rotation={[-0.16, -0.04, -0.09]} scale={[0.7, 1.18, 0.84]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_43__0.geometry} />
          </group>
          <group position={[-159.11, 0, 185.65]} rotation={[-0.12, -0.18, -0.03]} scale={[1.02, 1.39, 0.93]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_44__0.geometry} />
          </group>
          <group position={[-176.31, 0, 179.18]} rotation={[0.19, 0.05, 0.15]} scale={[0.79, 0.81, 1.04]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_45__0.geometry} />
          </group>
          <group position={[-100.03, 0, 162.49]} rotation={[0.11, -0.02, 0.07]} scale={[0.83, 0.65, 0.6]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_46__0.geometry} />
          </group>
          <group position={[-162.16, 0, 89.69]} rotation={[-0.02, 0, 0.12]} scale={[1.46, 1.28, 0.64]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_47__0.geometry} />
          </group>
          <group position={[-157.4, 0, 87.34]} rotation={[0.13, 0.11, -0.02]} scale={[0.68, 0.54, 0.7]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_48__0.geometry} />
          </group>
          <group position={[-159.35, 0, -21.54]} rotation={[0.08, 0.07, -0.07]} scale={[0.68, 1.48, 1.35]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_49__0.geometry} />
          </group>
          <group position={[-118.07, 0, 3.33]} rotation={[-0.03, -0.02, 0.13]} scale={[0.94, 1.12, 0.75]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_50__0.geometry} />
          </group>
          <group position={[-109.75, 0, -85.75]} rotation={[-0.02, 0.1, -0.16]} scale={[1.09, 1.07, 1]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_51__0.geometry} />
          </group>
          <group position={[-136.64, 0, -95.14]} rotation={[-0.08, -0.06, -0.02]} scale={[0.69, 1.02, 1.21]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_52__0.geometry} />
          </group>
          <group position={[-95.69, 0, -63.48]} rotation={[0.06, 0.02, 0.17]} scale={[0.81, 0.85, 0.52]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_53__0.geometry} />
          </group>
          <group position={[-126.84, 0, -141.74]} rotation={[0.1, -0.07, 0.2]} scale={[1.27, 0.6, 0.66]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_54__0.geometry} />
          </group>
          <group position={[-99.73, 0, -113.54]} rotation={[-0.11, 0.13, 0.05]} scale={[1.36, 0.55, 0.54]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_55__0.geometry} />
          </group>
          <group position={[-97, 0, -213.92]} rotation={[0.14, -0.08, 0.2]} scale={[0.8, 0.62, 0.93]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_56__0.geometry} />
          </group>
          <group position={[-143.88, 0, -210.24]} rotation={[0.09, -0.08, -0.03]} scale={[1.08, 1.12, 1.46]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_57__0.geometry} />
          </group>
          <group position={[-113.73, 0, -203.19]} rotation={[-0.16, -0.1, -0.03]} scale={[1.22, 0.5, 1.1]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_58__0.geometry} />
          </group>
          <group position={[-134.01, 0, -283.37]} rotation={[-0.15, -0.02, -0.09]} scale={[1.11, 1.29, 0.68]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_59__0.geometry} />
          </group>
          <group position={[-80.33, 0, 271.17]} rotation={[0.15, 0.17, 0.05]} scale={[1.21, 1.33, 1.27]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_60__0.geometry} />
          </group>
          <group position={[-73.79, 0, 279.38]} rotation={[-0.14, -0.04, -0.18]} scale={[1.17, 0.86, 1.03]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_61__0.geometry} />
          </group>
          <group position={[-113.6, 0, 251.69]} rotation={[0.08, -0.07, -0.08]} scale={[1.27, 1.27, 0.92]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_62__0.geometry} />
          </group>
          <group position={[-90.37, 0, 162.55]} rotation={[-0.13, 0.19, 0.17]} scale={[1.09, 1.02, 1.07]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_63__0.geometry} />
          </group>
          <group position={[-114.37, 0, 171.83]} rotation={[0.02, -0.09, 0.08]} scale={[1.27, 1.29, 1.18]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_64__0.geometry} />
          </group>
          <group position={[-99.99, 0, 113.16]} rotation={[0.19, -0.01, -0.17]} scale={[1.12, 0.86, 0.66]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_65__0.geometry} />
          </group>
          <group position={[-113.6, 0, 34.43]} rotation={[-0.03, 0, -0.02]} scale={[0.82, 0.94, 1.33]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_66__0.geometry} />
          </group>
          <group position={[-145.76, 0, 28.92]} rotation={[0.06, 0.16, -0.04]} scale={[1.32, 0.54, 1.43]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_67__0.geometry} />
          </group>
          <group position={[-128.94, 0, -6.58]} rotation={[0.09, -0.11, -0.15]} scale={[0.55, 0.75, 1.49]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_68__0.geometry} />
          </group>
          <group position={[-105.18, 0, 6.83]} rotation={[0.14, -0.15, -0.15]} scale={[0.98, 0.97, 0.5]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_69__0.geometry} />
          </group>
          <group position={[-119.09, 0, -54.52]} rotation={[0.08, -0.15, 0.06]} scale={[0.61, 1.48, 1.08]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_70__0.geometry} />
          </group>
          <group position={[-72.47, 0, -58.41]} rotation={[0.17, 0.14, -0.01]} scale={[0.94, 0.57, 0.8]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_71__0.geometry} />
          </group>
          <group position={[-141.15, 0, -104.23]} rotation={[-0.01, 0.13, 0.1]} scale={[1.2, 0.53, 0.69]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_72__0.geometry} />
          </group>
          <group position={[-87.98, 0, -161.53]} rotation={[0.19, 0.05, 0.08]} scale={[0.61, 0.91, 0.84]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_73__0.geometry} />
          </group>
          <group position={[-102.59, 0, -200.41]} rotation={[0.02, 0.07, -0.06]} scale={[1.48, 1.35, 0.99]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_74__0.geometry} />
          </group>
          <group position={[-66.51, 0, -144.81]} rotation={[0.17, -0.15, 0.09]} scale={[0.7, 1.26, 0.87]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_75__0.geometry} />
          </group>
          <group position={[-95.43, 0, -201.73]} rotation={[0.16, -0.21, 0.06]} scale={[1.07, 1.19, 1.25]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_76__0.geometry} />
          </group>
          <group position={[-58.63, 0, -241.27]} rotation={[0.1, 0.11, 0.05]} scale={[1.22, 1.11, 1.25]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_77__0.geometry} />
          </group>
          <group position={[-146.69, 0, -303.02]} rotation={[-0.01, 0.1, -0.13]} scale={[0.75, 0.98, 0.69]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_78__0.geometry} />
          </group>
          <group position={[-56.69, 0, -338.08]} rotation={[0.04, 0.1, -0.04]} scale={[1.26, 1.08, 1.5]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_79__0.geometry} />
          </group>
          <group position={[-100.7, 0, 325.43]} rotation={[0.14, -0.07, 0.06]} scale={[0.63, 1.41, 1.37]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_80__0.geometry} />
          </group>
          <group position={[-62.19, 0, 290.92]} rotation={[0.15, -0.14, -0.11]} scale={[0.8, 1.48, 1.21]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_81__0.geometry} />
          </group>
          <group position={[-48.05, 0, 261.62]} rotation={[0.01, -0.17, 0.1]} scale={[0.87, 0.72, 1.24]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_82__0.geometry} />
          </group>
          <group position={[-99.01, 0, 160.43]} rotation={[-0.06, 0.15, 0.16]} scale={[1.18, 0.94, 0.91]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_83__0.geometry} />
          </group>
          <group position={[-56.73, 0, 214.84]} rotation={[-0.07, 0.08, -0.19]} scale={[1.01, 0.74, 1.28]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_84__0.geometry} />
          </group>
          <group position={[-59, 0, 180.07]} rotation={[0.03, -0.03, -0.07]} scale={[0.88, 1.04, 0.6]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_85__0.geometry} />
          </group>
          <group position={[-99.79, 0, 93.41]} rotation={[-0.15, 0.05, -0.2]} scale={[0.53, 0.91, 1.43]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_86__0.geometry} />
          </group>
          <group position={[-111.1, 0, 69.08]} rotation={[0.1, 0.09, -0.16]} scale={[0.96, 0.92, 0.82]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_87__0.geometry} />
          </group>
          <group position={[-105.74, 0, 52.48]} rotation={[0.01, -0.08, 0]} scale={[1.27, 1.24, 0.78]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_88__0.geometry} />
          </group>
          <group position={[-35.77, 0, -6.33]} rotation={[0, 0.09, -0.13]} scale={[0.98, 0.52, 0.9]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_89__0.geometry} />
          </group>
          <group position={[-113.03, 0, 24.29]} rotation={[-0.08, 0.12, -0.06]} scale={[1.07, 0.53, 1.3]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_90__0.geometry} />
          </group>
          <group position={[-45.16, 0, 11.15]} rotation={[-0.11, -0.15, 0.03]} scale={[1.03, 0.83, 0.9]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_91__0.geometry} />
          </group>
          <group position={[-56.04, 0, -31.37]} rotation={[-0.05, -0.15, 0.02]} scale={[1.35, 1.22, 1.38]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_92__0.geometry} />
          </group>
          <group position={[-31.74, 0, -55.38]} rotation={[-0.03, 0.2, -0.06]} scale={[0.98, 0.72, 1.39]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_93__0.geometry} />
          </group>
          <group position={[-49.7, 0, -163.52]} rotation={[-0.16, 0.2, -0.1]} scale={[1.25, 1.24, 0.85]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_94__0.geometry} />
          </group>
          <group position={[-108.72, 0, -132.46]} rotation={[0.06, -0.16, 0.2]} scale={[0.85, 0.78, 0.88]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_95__0.geometry} />
          </group>
          <group position={[-113.7, 0, -140.87]} rotation={[0.11, 0.05, -0.01]} scale={[0.54, 0.54, 0.55]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_96__0.geometry} />
          </group>
          <group position={[-53.27, 0, -261.12]} rotation={[0.03, 0.15, -0.11]} scale={[0.91, 0.78, 1.32]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_97__0.geometry} />
          </group>
          <group position={[-27.26, 0, -267.26]} rotation={[0.09, 0.17, 0.04]} scale={[1.29, 1.13, 1.35]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_98__0.geometry} />
          </group>
          <group position={[-31.71, 0, -275.4]} rotation={[-0.07, -0.2, 0.01]} scale={[1.22, 0.97, 0.65]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_99__0.geometry} />
          </group>
          <group position={[-14.41, 0, 254.2]} rotation={[-0.04, 0.19, -0.12]} scale={[1.1, 0.65, 0.51]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_100__0.geometry} />
          </group>
          <group position={[-6.67, 0, 207.26]} rotation={[-0.1, 0.12, 0.15]} scale={[1.41, 1.12, 1.26]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_101__0.geometry} />
          </group>
          <group position={[-12.87, 0, 205.62]} rotation={[0.05, 0.05, -0.06]} scale={[1.15, 1.09, 1.35]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_102__0.geometry} />
          </group>
          <group position={[-34.5, 0, 201.22]} rotation={[0.14, 0.16, 0.17]} scale={[0.88, 0.97, 0.71]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_103__0.geometry} />
          </group>
          <group position={[2.27, 0, 130.81]} rotation={[0.16, -0.21, -0.12]} scale={[0.97, 0.97, 1.14]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_104__0.geometry} />
          </group>
          <group position={[-28.82, 0, 155.09]} rotation={[0.1, -0.15, -0.09]} scale={[1.16, 1.3, 0.5]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_105__0.geometry} />
          </group>
          <group position={[-73.8, 0, 126.88]} rotation={[-0.07, -0.11, -0.07]} scale={[1.06, 1.01, 0.72]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_106__0.geometry} />
          </group>
          <group position={[-1.58, 0, 14.31]} rotation={[-0.15, -0.11, 0.04]} scale={[0.52, 0.64, 1.32]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_107__0.geometry} />
          </group>
          <group position={[-9.64, 0, -25.77]} rotation={[0.15, 0.14, 0.07]} scale={[0.89, 0.58, 1.26]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_108__0.geometry} />
          </group>
          <group position={[-39.06, 0, -27.27]} rotation={[-0.07, -0.19, 0.08]} scale={[0.76, 1.38, 0.95]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_109__0.geometry} />
          </group>
          <group position={[-95.4, 0, -12.31]} rotation={[-0.08, 0.18, 0.03]} scale={[1.24, 0.87, 0.71]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_110__0.geometry} />
          </group>
          <group position={[-9.42, 0, -49.71]} rotation={[-0.02, 0.17, -0.17]} scale={[1.24, 1.01, 0.59]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_111__0.geometry} />
          </group>
          <group position={[-30.26, 0, -115.4]} rotation={[0.05, -0.13, 0.14]} scale={[1.09, 1.06, 1.03]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_112__0.geometry} />
          </group>
          <group position={[-46.84, 0, -159.67]} rotation={[-0.07, 0.03, 0.1]} scale={[1.28, 1.23, 1.23]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_113__0.geometry} />
          </group>
          <group position={[-88.2, 0, -189.64]} rotation={[-0.17, 0.01, -0.1]} scale={[0.75, 0.83, 0.59]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_114__0.geometry} />
          </group>
          <group position={[-67.7, 0, -198.76]} rotation={[-0.14, -0.07, 0.14]} scale={[0.6, 1.17, 1.14]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_115__0.geometry} />
          </group>
          <group position={[-12.83, 0, -266.06]} rotation={[0.06, 0.07, -0.2]} scale={[0.94, 1.27, 0.67]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_116__0.geometry} />
          </group>
          <group position={[-38.37, 0, -230.24]} rotation={[0.07, -0.1, -0.08]} scale={[0.9, 1.29, 1.39]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_117__0.geometry} />
          </group>
          <group position={[-95.27, 0, -237.93]} rotation={[0.06, 0.07, 0.05]} scale={[0.53, 1.33, 0.8]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_118__0.geometry} />
          </group>
          <group position={[-22.51, 0, -266.53]} rotation={[-0.1, 0.14, 0.08]} scale={[1.35, 0.63, 1.23]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_119__0.geometry} />
          </group>
          <group position={[24.16, 0, 269.92]} rotation={[0.07, -0.17, 0.06]} scale={[0.51, 0.89, 1.19]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_120__0.geometry} />
          </group>
          <group position={[-22.14, 0, 217.49]} rotation={[-0.08, -0.07, 0.08]} scale={[0.91, 1.07, 1.11]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_121__0.geometry} />
          </group>
          <group position={[33.03, 0, 191.95]} rotation={[-0.18, 0.07, 0.21]} scale={[1.46, 1.46, 0.94]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_122__0.geometry} />
          </group>
          <group position={[-26.18, 0, 247.37]} rotation={[-0.18, -0.1, 0.03]} scale={[0.9, 1.1, 1.13]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_123__0.geometry} />
          </group>
          <group position={[-40.75, 0, 188.29]} rotation={[-0.17, 0.07, -0.09]} scale={[1.5, 0.76, 1.45]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_124__0.geometry} />
          </group>
          <group position={[-62.81, 0, 127.92]} rotation={[-0.17, -0.02, -0.07]} scale={[0.52, 1.22, 0.64]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_125__0.geometry} />
          </group>
          <group position={[-20.23, 0, 138.39]} rotation={[-0.12, -0.01, 0]} scale={[0.6, 1.49, 0.84]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_126__0.geometry} />
          </group>
          <group position={[-28.35, 0, 113.01]} rotation={[0.13, -0.04, 0.02]} scale={[0.69, 1.14, 0.83]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_127__0.geometry} />
          </group>
          <group position={[-51.23, 0, 38.86]} rotation={[0.09, 0.1, 0.19]} scale={[0.58, 0.54, 1.05]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_128__0.geometry} />
          </group>
          <group position={[22.84, 0, 9.37]} rotation={[0.12, -0.19, -0.13]} scale={[0.7, 1.21, 1.46]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_129__0.geometry} />
          </group>
          <group position={[-43.34, 0, -3.54]} rotation={[0.08, 0.13, 0.11]} scale={[1.31, 0.83, 0.92]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_130__0.geometry} />
          </group>
          <group position={[13.24, 0, 8.78]} rotation={[0.03, -0.14, 0.08]} scale={[1.45, 0.76, 0.51]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_131__0.geometry} />
          </group>
          <group position={[-20.53, 0, -101.61]} rotation={[0.2, -0.1, -0.15]} scale={[0.53, 0.85, 0.6]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_132__0.geometry} />
          </group>
          <group position={[23.81, 0, -86.22]} rotation={[-0.03, -0.07, 0.19]} scale={[0.51, 1.44, 0.8]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_133__0.geometry} />
          </group>
          <group position={[-18.2, 0, -96.31]} rotation={[0.1, 0, 0.2]} scale={[0.58, 1.41, 0.93]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_134__0.geometry} />
          </group>
          <group position={[-7.21, 0, -141.07]} rotation={[-0.09, 0.17, -0.16]} scale={[0.57, 1.2, 1.08]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_135__0.geometry} />
          </group>
          <group position={[-43.32, 0, -224.95]} rotation={[0.16, -0.15, 0.08]} scale={[1.23, 0.51, 0.72]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_136__0.geometry} />
          </group>
          <group position={[-27.06, 0, -177.81]} rotation={[0.02, -0.08, 0.2]} scale={[1.16, 0.97, 1.14]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_137__0.geometry} />
          </group>
          <group position={[-20.74, 0, -265.76]} rotation={[-0.06, -0.09, 0.19]} scale={[1.09, 0.62, 0.59]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_138__0.geometry} />
          </group>
          <group position={[-10.97, 0, -302.64]} rotation={[-0.05, 0.13, 0.19]} scale={[0.54, 1.21, 1.18]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_139__0.geometry} />
          </group>
          <group position={[36.18, 0, 266.68]} rotation={[-0.15, 0.11, -0.06]} scale={[0.86, 0.88, 1.33]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_140__0.geometry} />
          </group>
          <group position={[35.67, 0, 195.7]} rotation={[-0.06, -0.15, 0.15]} scale={[1.23, 0.68, 0.71]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_141__0.geometry} />
          </group>
          <group position={[-17.03, 0, 248.11]} rotation={[-0.07, 0.1, 0.2]} scale={[1.48, 0.87, 0.96]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_142__0.geometry} />
          </group>
          <group position={[15.53, 0, 142.01]} rotation={[-0.04, -0.1, -0.06]} scale={[0.7, 0.9, 0.93]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_143__0.geometry} />
          </group>
          <group position={[57.38, 0, 168.87]} rotation={[-0.09, -0.19, 0.12]} scale={[1.37, 1, 0.66]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_144__0.geometry} />
          </group>
          <group position={[-30.42, 0, 125.52]} rotation={[-0.02, 0.06, -0.2]} scale={[1.33, 0.87, 1.18]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_145__0.geometry} />
          </group>
          <group position={[-21.94, 0, 117.02]} rotation={[-0.05, -0.05, 0.13]} scale={[1.27, 0.92, 1.09]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_146__0.geometry} />
          </group>
          <group position={[-15.94, 0, 38.85]} rotation={[0.15, -0.15, 0.02]} scale={[1.23, 0.52, 0.9]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_147__0.geometry} />
          </group>
          <group position={[-8.12, 0, 38.46]} rotation={[-0.02, -0.1, -0.02]} scale={[0.67, 1.5, 1.44]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_148__0.geometry} />
          </group>
          <group position={[31.48, 0, 25.12]} rotation={[-0.09, 0.12, 0.09]} scale={[0.61, 1.24, 0.55]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_149__0.geometry} />
          </group>
          <group position={[-31.48, 0, -42.9]} rotation={[-0.14, -0.07, 0.06]} scale={[0.91, 0.93, 0.96]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_150__0.geometry} />
          </group>
          <group position={[32.72, 0, -56.88]} rotation={[0.18, -0.11, 0.01]} scale={[0.68, 1.29, 1.34]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_151__0.geometry} />
          </group>
          <group position={[10.71, 0, -91.65]} rotation={[-0.04, 0, -0.11]} scale={[1.49, 1.02, 0.74]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_152__0.geometry} />
          </group>
          <group position={[-2.44, 0, -102.13]} rotation={[0.1, 0.11, -0.16]} scale={[1.37, 1.36, 1.35]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_153__0.geometry} />
          </group>
          <group position={[49.3, 0, -110.54]} rotation={[-0.07, -0.16, -0.22]} scale={[1.44, 0.65, 1.07]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_154__0.geometry} />
          </group>
          <group position={[59.2, 0, -203.48]} rotation={[0.07, -0.08, 0.08]} scale={[0.84, 0.5, 1.49]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_155__0.geometry} />
          </group>
          <group position={[-15.94, 0, -241.12]} rotation={[-0.19, 0.2, 0.03]} scale={[1.36, 1.14, 1]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_156__0.geometry} />
          </group>
          <group position={[-26.86, 0, -276.84]} rotation={[-0.17, -0.07, -0.13]} scale={[1.23, 1.35, 1.34]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_157__0.geometry} />
          </group>
          <group position={[-27.94, 0, -240.98]} rotation={[-0.03, 0.06, -0.19]} scale={[1.17, 1.32, 0.76]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_158__0.geometry} />
          </group>
          <group position={[11, 0, -331.99]} rotation={[-0.08, -0.09, -0.19]} scale={[1.39, 1.24, 0.8]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_159__0.geometry} />
          </group>
          <group position={[71.51, 0, 342.39]} rotation={[-0.06, -0.07, -0.02]} scale={[0.77, 1.4, 0.59]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_160__0.geometry} />
          </group>
          <group position={[12.47, 0, 294.58]} rotation={[-0.19, -0.08, -0.09]} scale={[1.04, 0.97, 0.58]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_161__0.geometry} />
          </group>
          <group position={[37.21, 0, 232.93]} rotation={[0.11, 0.12, -0.17]} scale={[1.03, 0.98, 0.62]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_162__0.geometry} />
          </group>
          <group position={[27.7, 0, 217.21]} rotation={[-0.11, -0.16, -0.03]} scale={[1.14, 0.71, 0.82]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_163__0.geometry} />
          </group>
          <group position={[10.48, 0, 182.55]} rotation={[-0.15, 0.12, 0.07]} scale={[0.82, 0.56, 1.47]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_164__0.geometry} />
          </group>
          <group position={[18.74, 0, 169.98]} rotation={[0.04, 0.11, -0.15]} scale={[1.14, 0.96, 1.29]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_165__0.geometry} />
          </group>
          <group position={[95.15, 0, 125.4]} rotation={[0.16, -0.09, -0.04]} scale={[0.72, 0.74, 1.06]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_166__0.geometry} />
          </group>
          <group position={[80.74, 0, 64.76]} rotation={[-0.15, 0.03, 0.07]} scale={[1.14, 0.67, 0.82]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_167__0.geometry} />
          </group>
          <group position={[66.98, 0, 13.58]} rotation={[0.17, 0.03, -0.06]} scale={[0.5, 0.7, 1.4]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_168__0.geometry} />
          </group>
          <group position={[50.94, 0, 35.32]} rotation={[0.04, 0.12, -0.14]} scale={[0.95, 0.69, 1.23]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_169__0.geometry} />
          </group>
          <group position={[-4.19, 0, 39]} rotation={[-0.11, -0.03, -0.13]} scale={[0.54, 0.52, 1.46]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_170__0.geometry} />
          </group>
          <group position={[12.23, 0, -3.03]} rotation={[-0.15, 0.1, 0.09]} scale={[0.61, 0.9, 0.68]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_171__0.geometry} />
          </group>
          <group position={[1.83, 0, -107.47]} rotation={[0.16, -0.01, -0.01]} scale={[1, 1.13, 1.14]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_172__0.geometry} />
          </group>
          <group position={[53.18, 0, -146.53]} rotation={[-0.18, -0.05, 0.04]} scale={[0.65, 0.9, 1.03]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_173__0.geometry} />
          </group>
          <group position={[14.43, 0, -119.48]} rotation={[-0.04, -0.18, 0.1]} scale={[1, 1.05, 0.84]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_174__0.geometry} />
          </group>
          <group position={[63.4, 0, -199.4]} rotation={[-0.07, -0.03, 0.07]} scale={[0.88, 1.2, 1.24]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_175__0.geometry} />
          </group>
          <group position={[16.32, 0, -150.46]} rotation={[0.05, 0.05, 0.06]} scale={[0.9, 0.94, 1.1]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_176__0.geometry} />
          </group>
          <group position={[33.05, 0, -199.85]} rotation={[0.15, -0.11, -0.08]} scale={[0.84, 0.85, 1.28]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_177__0.geometry} />
          </group>
          <group position={[92.9, 0, -258.58]} rotation={[0.19, -0.16, -0.04]} scale={[0.99, 1.43, 0.6]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_178__0.geometry} />
          </group>
          <group position={[94.24, 0, -244.79]} rotation={[-0.1, 0.2, 0.08]} scale={[1.43, 0.86, 0.57]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_179__0.geometry} />
          </group>
          <group position={[85.19, 0, 297.96]} rotation={[0.21, 0.15, 0.17]} scale={[0.97, 1.01, 0.99]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_180__0.geometry} />
          </group>
          <group position={[59.3, 0, 246.48]} rotation={[0.03, -0.07, 0.19]} scale={[0.98, 1.38, 0.7]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_181__0.geometry} />
          </group>
          <group position={[79.3, 0, 189.68]} rotation={[-0.05, 0.09, -0.18]} scale={[0.67, 1.26, 1.21]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_182__0.geometry} />
          </group>
          <group position={[39.66, 0, 167.3]} rotation={[-0.07, -0.11, 0.18]} scale={[1.09, 1.13, 1.43]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_183__0.geometry} />
          </group>
          <group position={[34.73, 0, 100.68]} rotation={[0.02, -0.06, 0.03]} scale={[1.27, 1.27, 0.84]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_184__0.geometry} />
          </group>
          <group position={[99.14, 0, 121.94]} rotation={[0.02, 0.12, 0.16]} scale={[0.58, 1.34, 1.35]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_185__0.geometry} />
          </group>
          <group position={[98.43, 0, 94.47]} rotation={[-0.05, -0.16, 0.07]} scale={[0.87, 1.4, 1.35]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_186__0.geometry} />
          </group>
          <group position={[97.56, 0, 5.28]} rotation={[-0.2, 0.06, 0.07]} scale={[1.43, 0.56, 1.32]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_187__0.geometry} />
          </group>
          <group position={[80.1, 0, -1.9]} rotation={[-0.02, 0.18, 0.11]} scale={[1.24, 1.25, 0.89]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_188__0.geometry} />
          </group>
          <group position={[71.85, 0, 0.65]} rotation={[-0.17, 0.08, 0.12]} scale={[0.74, 0.91, 0.97]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_189__0.geometry} />
          </group>
          <group position={[42.55, 0, -86.1]} rotation={[-0.18, -0.01, 0.05]} scale={[1.17, 0.52, 0.54]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_190__0.geometry} />
          </group>
          <group position={[100.2, 0, -96.94]} rotation={[-0.09, 0.03, 0.19]} scale={[0.68, 0.81, 1.36]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_191__0.geometry} />
          </group>
          <group position={[124.87, 0, -106.42]} rotation={[-0.11, -0.16, 0.04]} scale={[0.58, 1.46, 0.91]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_192__0.geometry} />
          </group>
          <group position={[84.09, 0, -155.56]} rotation={[-0.17, -0.21, 0.01]} scale={[1.19, 1.19, 0.65]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_193__0.geometry} />
          </group>
          <group position={[60.32, 0, -133.03]} rotation={[0.05, -0.16, -0.05]} scale={[1.4, 0.53, 0.62]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_194__0.geometry} />
          </group>
          <group position={[109.65, 0, -209.35]} rotation={[-0.13, 0.03, 0.19]} scale={[0.86, 0.73, 0.58]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_195__0.geometry} />
          </group>
          <group position={[37, 0, -198.16]} rotation={[0.1, 0.1, -0.04]} scale={[0.53, 0.76, 1.2]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_196__0.geometry} />
          </group>
          <group position={[123.72, 0, -254.48]} rotation={[0.09, 0.08, 0.08]} scale={[1.35, 0.61, 0.83]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_197__0.geometry} />
          </group>
          <group position={[33.04, 0, -280.03]} rotation={[0.05, 0.07, -0.02]} scale={[0.74, 0.87, 1.08]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_198__0.geometry} />
          </group>
          <group position={[88.81, 0, -280.19]} rotation={[0.09, 0.16, -0.02]} scale={[0.71, 1.38, 0.57]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_199__0.geometry} />
          </group>
          <group position={[58.98, 0, 256.68]} rotation={[-0.19, 0.05, 0.06]} scale={[1.4, 1.29, 1.04]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_200__0.geometry} />
          </group>
          <group position={[132.26, 0, 302.69]} rotation={[-0.11, -0.05, -0.1]} scale={[0.61, 0.55, 0.74]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_201__0.geometry} />
          </group>
          <group position={[71, 0, 208.65]} rotation={[0.19, -0.2, 0.02]} scale={[1.2, 1.01, 0.76]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_202__0.geometry} />
          </group>
          <group position={[143.34, 0, 243.42]} rotation={[0.18, 0.15, -0.09]} scale={[1.06, 0.78, 1.28]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_203__0.geometry} />
          </group>
          <group position={[59.92, 0, 199.78]} rotation={[-0.08, -0.17, -0.17]} scale={[0.9, 1.07, 0.73]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_204__0.geometry} />
          </group>
          <group position={[126.42, 0, 190.39]} rotation={[0, 0.05, 0.2]} scale={[1.28, 0.78, 1.4]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_205__0.geometry} />
          </group>
          <group position={[112.8, 0, 143.24]} rotation={[-0.12, -0.18, -0.13]} scale={[0.68, 0.9, 0.84]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_206__0.geometry} />
          </group>
          <group position={[79.77, 0, 133.12]} rotation={[0.02, -0.03, -0.06]} scale={[1.02, 0.93, 0.96]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_207__0.geometry} />
          </group>
          <group position={[93.78, 0, 15.63]} rotation={[0.16, 0.04, 0.04]} scale={[1.2, 0.82, 1.03]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_208__0.geometry} />
          </group>
          <group position={[95.19, 0, 23.02]} rotation={[-0.06, -0.1, 0.11]} scale={[1.43, 0.98, 1.23]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_209__0.geometry} />
          </group>
          <group position={[66.63, 0, -13.99]} rotation={[0.09, 0.14, -0.1]} scale={[1.28, 0.79, 0.61]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_210__0.geometry} />
          </group>
          <group position={[81.44, 0, -37.53]} rotation={[-0.08, 0.01, 0]} scale={[1, 1.13, 0.8]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_211__0.geometry} />
          </group>
          <group position={[116.72, 0, -54.25]} rotation={[0.07, -0.06, -0.16]} scale={[1.21, 1.11, 1.08]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_212__0.geometry} />
          </group>
          <group position={[88.16, 0, -114.59]} rotation={[-0.09, 0.13, -0.09]} scale={[1.18, 1.02, 1.47]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_213__0.geometry} />
          </group>
          <group position={[121.68, 0, -140.27]} rotation={[0.14, -0.15, 0.12]} scale={[1.13, 1.31, 0.93]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_214__0.geometry} />
          </group>
          <group position={[92.79, 0, -148.47]} rotation={[0.04, 0.01, -0.11]} scale={[0.66, 0.94, 1.5]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_215__0.geometry} />
          </group>
          <group position={[127.65, 0, -152.85]} rotation={[-0.04, -0.02, -0.16]} scale={[1.02, 0.51, 0.75]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_216__0.geometry} />
          </group>
          <group position={[121.58, 0, -268.41]} rotation={[0.11, -0.12, -0.01]} scale={[1.45, 1.26, 1.29]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_217__0.geometry} />
          </group>
          <group position={[68.69, 0, -223.08]} rotation={[0.15, -0.06, 0.11]} scale={[1.48, 1.01, 1.01]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_218__0.geometry} />
          </group>
          <group position={[113.6, 0, -299.84]} rotation={[-0.15, 0, 0.09]} scale={[0.75, 0.86, 1.17]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_219__0.geometry} />
          </group>
          <group position={[139.96, 0, 216.92]} rotation={[0.02, 0.19, -0.04]} scale={[1.02, 0.71, 1.35]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_220__0.geometry} />
          </group>
          <group position={[172.54, 0, 211.5]} rotation={[-0.02, -0.11, -0.06]} scale={[0.92, 0.57, 1.01]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_221__0.geometry} />
          </group>
          <group position={[112.57, 0, 236.85]} rotation={[-0.1, -0.1, -0.2]} scale={[1.15, 1.34, 1.22]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_222__0.geometry} />
          </group>
          <group position={[148.56, 0, 194.47]} rotation={[-0.1, -0.04, -0.03]} scale={[1.28, 1.17, 0.84]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_223__0.geometry} />
          </group>
          <group position={[142, 0, 179.25]} rotation={[-0.02, 0.1, -0.02]} scale={[0.57, 1.27, 0.62]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_224__0.geometry} />
          </group>
          <group position={[181.53, 0, 159.34]} rotation={[0.15, 0.06, 0.16]} scale={[1.14, 1.35, 1.09]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_225__0.geometry} />
          </group>
          <group position={[109.75, 0, 111.41]} rotation={[-0.04, 0.12, 0.11]} scale={[1.23, 1.36, 0.7]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_226__0.geometry} />
          </group>
          <group position={[107.39, 0, 45.32]} rotation={[-0.08, -0.17, 0.01]} scale={[0.67, 0.82, 1.05]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_227__0.geometry} />
          </group>
          <group position={[160.56, 0, 40.34]} rotation={[0.06, 0.08, 0.15]} scale={[0.85, 1.1, 1.23]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_228__0.geometry} />
          </group>
          <group position={[139.98, 0, -13.49]} rotation={[0, -0.06, 0.06]} scale={[1.46, 1.11, 0.52]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_229__0.geometry} />
          </group>
          <group position={[119.43, 0, -49.4]} rotation={[-0.02, 0.03, -0.13]} scale={[1.14, 1.03, 1.44]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_230__0.geometry} />
          </group>
          <group position={[107.1, 0, -73.39]} rotation={[0.15, -0.12, -0.11]} scale={[1.36, 0.95, 0.7]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_231__0.geometry} />
          </group>
          <group position={[130.36, 0, -92.9]} rotation={[0.17, 0.01, -0.18]} scale={[0.63, 1.27, 1.32]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_232__0.geometry} />
          </group>
          <group position={[128.36, 0, -87.47]} rotation={[-0.16, 0.17, 0.18]} scale={[0.93, 0.99, 1.1]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_233__0.geometry} />
          </group>
          <group position={[146.84, 0, -171.82]} rotation={[0.1, -0.17, 0.14]} scale={[0.72, 1.36, 0.55]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_234__0.geometry} />
          </group>
          <group position={[117.05, 0, -228]} rotation={[-0.14, 0.11, 0.18]} scale={[0.68, 0.99, 0.64]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_235__0.geometry} />
          </group>
          <group position={[183.68, 0, -225.03]} rotation={[0.09, -0.1, 0.21]} scale={[0.75, 1.2, 1.5]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_236__0.geometry} />
          </group>
          <group position={[181.45, 0, -223.1]} rotation={[-0.05, -0.07, 0.12]} scale={[0.59, 0.9, 1.28]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_237__0.geometry} />
          </group>
          <group position={[167.53, 0, -241.82]} rotation={[-0.07, -0.19, 0.1]} scale={[0.74, 1.41, 0.55]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_238__0.geometry} />
          </group>
          <group position={[98.31, 0, -302.31]} rotation={[0.15, 0.01, 0.08]} scale={[1.31, 0.73, 1.25]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_239__0.geometry} />
          </group>
          <group position={[117.93, 0, 281.31]} rotation={[-0.2, 0.04, -0.09]} scale={[0.86, 0.8, 0.95]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_240__0.geometry} />
          </group>
          <group position={[201.06, 0, 265.65]} rotation={[0.2, 0.09, -0.19]} scale={[1.47, 1.44, 1.21]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_241__0.geometry} />
          </group>
          <group position={[165.5, 0, 203.46]} rotation={[0.18, -0.04, 0.09]} scale={[1.38, 1.38, 1.16]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_242__0.geometry} />
          </group>
          <group position={[132.73, 0, 210.45]} rotation={[0.11, -0.13, 0.11]} scale={[1.24, 1.37, 1.43]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_243__0.geometry} />
          </group>
          <group position={[148.93, 0, 146.23]} rotation={[0.17, -0.15, -0.15]} scale={[1.35, 0.84, 0.8]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_244__0.geometry} />
          </group>
          <group position={[186.49, 0, 112.09]} rotation={[-0.21, 0.07, -0.03]} scale={[0.63, 1.34, 1.41]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_245__0.geometry} />
          </group>
          <group position={[168.08, 0, 123.24]} rotation={[0.19, -0.15, 0.13]} scale={[0.99, 0.56, 0.61]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_246__0.geometry} />
          </group>
          <group position={[186.89, 0, 84.92]} rotation={[-0.12, -0.16, -0.03]} scale={[1.45, 1.12, 1.26]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_247__0.geometry} />
          </group>
          <group position={[214.03, 0, 65.66]} rotation={[0.17, 0.02, 0.06]} scale={[1, 0.84, 0.58]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_248__0.geometry} />
          </group>
          <group position={[209.45, 0, -26.04]} rotation={[0.04, 0.18, -0.03]} scale={[0.65, 0.74, 0.84]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_249__0.geometry} />
          </group>
          <group position={[216.5, 0, -50.54]} rotation={[0.09, -0.11, -0.02]} scale={[0.84, 0.71, 0.89]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_250__0.geometry} />
          </group>
          <group position={[212.65, 0, -62.18]} rotation={[0.19, 0.15, -0.03]} scale={[1.31, 1.11, 0.82]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_251__0.geometry} />
          </group>
          <group position={[178.12, 0, -109.96]} rotation={[0.08, 0.14, 0]} scale={[1.19, 0.86, 0.91]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_252__0.geometry} />
          </group>
          <group position={[148.75, 0, -141.92]} rotation={[-0.09, -0.11, -0.16]} scale={[0.85, 0.83, 0.89]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_253__0.geometry} />
          </group>
          <group position={[200.32, 0, -149.56]} rotation={[0.2, -0.03, -0.11]} scale={[0.99, 1.48, 0.94]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_254__0.geometry} />
          </group>
          <group position={[174.77, 0, -205.21]} rotation={[-0.08, -0.1, 0.12]} scale={[0.87, 1.27, 1.23]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_255__0.geometry} />
          </group>
          <group position={[206.69, 0, -146.48]} rotation={[0.08, 0.14, -0.18]} scale={[1.4, 0.59, 1.16]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_256__0.geometry} />
          </group>
          <group position={[211.69, 0, -205.51]} rotation={[0, 0.12, -0.07]} scale={[0.58, 1.29, 0.83]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_257__0.geometry} />
          </group>
          <group position={[194.85, 0, -228.66]} rotation={[0.01, -0.01, -0.2]} scale={[1.18, 1.35, 1.21]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_258__0.geometry} />
          </group>
          <group position={[207.34, 0, -322.76]} rotation={[-0.05, -0.19, -0.16]} scale={[1.09, 1.07, 0.67]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_259__0.geometry} />
          </group>
          <group position={[213.61, 0, 275.44]} rotation={[0.17, 0.12, -0.19]} scale={[0.51, 0.97, 1.32]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_260__0.geometry} />
          </group>
          <group position={[212.18, 0, 219.82]} rotation={[-0.09, 0.02, 0.03]} scale={[0.96, 1.06, 1.41]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_261__0.geometry} />
          </group>
          <group position={[184.25, 0, 198.77]} rotation={[0.08, -0.15, 0.06]} scale={[0.78, 0.92, 0.65]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_262__0.geometry} />
          </group>
          <group position={[244.14, 0, 193.52]} rotation={[0.12, -0.1, -0.04]} scale={[1.13, 0.56, 1.27]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_263__0.geometry} />
          </group>
          <group position={[241.64, 0, 130.59]} rotation={[0.11, 0.02, 0.05]} scale={[1, 0.84, 0.76]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_264__0.geometry} />
          </group>
          <group position={[226.02, 0, 103.51]} rotation={[-0.18, -0.04, 0.07]} scale={[1.4, 0.81, 1.19]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_265__0.geometry} />
          </group>
          <group position={[203.2, 0, 70.56]} rotation={[-0.09, -0.05, 0.09]} scale={[0.58, 0.79, 1.45]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_266__0.geometry} />
          </group>
          <group position={[218.38, 0, 93.46]} rotation={[-0.07, 0.17, 0.07]} scale={[0.74, 0.78, 0.65]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_267__0.geometry} />
          </group>
          <group position={[189.49, 0, -6.4]} rotation={[0, -0.2, 0.01]} scale={[1.33, 0.69, 1.16]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_268__0.geometry} />
          </group>
          <group position={[199.98, 0, -40.11]} rotation={[-0.14, 0.05, -0.02]} scale={[1.28, 0.7, 1.08]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_269__0.geometry} />
          </group>
          <group position={[186.2, 0, -38.8]} rotation={[-0.14, 0.05, 0.11]} scale={[0.73, 1.04, 0.64]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_270__0.geometry} />
          </group>
          <group position={[183.34, 0, -46.09]} rotation={[0.02, -0.04, 0.12]} scale={[0.92, 0.81, 1]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_271__0.geometry} />
          </group>
          <group position={[188.8, 0, -146.75]} rotation={[0.01, -0.11, -0.01]} scale={[0.6, 1.27, 1.24]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_272__0.geometry} />
          </group>
          <group position={[180.07, 0, -120.46]} rotation={[-0.21, 0.1, 0.16]} scale={[0.99, 0.71, 0.85]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_273__0.geometry} />
          </group>
          <group position={[202.63, 0, -136.08]} rotation={[-0.12, -0.04, -0.17]} scale={[1.36, 0.55, 0.93]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_274__0.geometry} />
          </group>
          <group position={[194.51, 0, -146.02]} rotation={[-0.02, -0.09, -0.04]} scale={[0.9, 0.73, 0.52]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_275__0.geometry} />
          </group>
          <group position={[244.92, 0, -197.65]} rotation={[-0.1, 0.2, 0.22]} scale={[0.94, 0.95, 0.59]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_276__0.geometry} />
          </group>
          <group position={[235.83, 0, -277.29]} rotation={[0.2, -0.18, 0.18]} scale={[0.93, 1.35, 1.06]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Med_277__0.geometry} />
          </group>
          <group position={[166.54, 0, -300.24]} rotation={[0.18, -0.02, -0.19]} scale={[1.27, 0.95, 0.83]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_High_278__0.geometry} />
          </group>
          <group position={[204.86, 0, -292.37]} rotation={[-0.11, -0.03, 0.05]} scale={[0.51, 0.68, 1.16]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.Grass_Low_279__0.geometry} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/grass/grass03/scene.gltf')
