/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: myochii (https://sketchfab.com/myochii)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/pine-tree-28db2fc0596348448f648e37cd13eb93
title: pine tree
*/

import React, { useRef, Suspense } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Tree01(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/trees/tree01/scene.gltf')
  return (
    <Suspense fallback={null}>
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.66, 0]}>
            <mesh
              material={materials.lambert1}
              geometry={nodes.group3_pasted__group1_pasted__pasted__pCone1_lambert1_0.geometry}
            />
          </group>
          <group position={[-0.7, 0.06, 0.11]} scale={[6.76, 6.76, 6.76]}>
            <mesh material={materials.lambert2} geometry={nodes.pPlane1_lambert2_0.geometry} />
          </group>
          <group position={[-0.84, 0.37, 0.18]} scale={[0.7, 0.7, 0.7]}>
            <mesh material={materials.lambert3} geometry={nodes.pCube3_lambert3_0.geometry} />
          </group>
        </group>
      </group>
    </group>
    </Suspense>
  )
}

useGLTF.preload('/models/trees/tree01/scene.gltf')
